# This is a basic workflow to help you get started with Actions
name: bicep-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'azure/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'azure/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checkout Code
    - uses: actions/checkout@v2
      
    # Login to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Deploy Bicep File
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP }}
        template: ./azure/funkysix.bicep
        parameters: projectEnvironment=dev
        failOnStdErr: false
        
